### ISSUE TITLE
Email Settings

### ISSUE THREAD

**Issue by syncolbysyn** [synapsestudios/oidc-platform#114]
# Description
The email settings screen will contain information about the status of the user's email(s) and also contain a form that will allow the user to change their email.

# ACs
- I can visit the email settings screen either by direct link from a client application or from a link on the profile screen.
- I will see the state of my email (verified or unverified)
- If my email is unverified I can click a link that will resend the verification email
- I can change my email address
  - Form contains two fields: new email and password
- Changing email triggers two emails 
  - to previous address - "email changed, if you didn't do this, contact ?"
  - to new address - "verify email"
- The new email shows up as pending verification with a "resend verification email" link
- Once a new email has been verified then the "new email" status section goes away and it just shows normal email state again.

# Tasks
- [x] Create the GET endpoint and the default template
- [x] Create the POST endpoint to trigger a verification email
- [x] Create the (get) endpoint to verify an email
- [x] Create the POST endpoint to change email
- [x] Add "new email" info to email settings template
- [x] Trigger the change email email to both email addresses
- [x] Handle new email reverify
- [x] Verifying the new email updates the user record to allow the user to login with the new email
- [x] POST to Undo email change
- [x] Return something a little more useful when the email is taken
