### ISSUE TITLE
Page Layout Templating

### ISSUE THREAD

**Issue by chrisheninger** [synapsestudios/oidc-platform#115]
# ACs
As a user I should be able to create new layouts and themes, and I should be able to select a theme for my OIDC client to use. A theme consists of a layout and theme files, all of which are optional. If the theme 

# Tasks
- [x] Create theme schema
- [x] Update page rendering to use theme file if available, otherwise use file on disk
- [x] Update email rendering to use theme file if available, otherwise use file on disk
- [x] Documentation

**Comment by spruce-bruce** [comment]
Could we fix this by making the whole layout template a configurable thing per client (the same way the login and email templates are configurable)? I think that gives the most flexibility with also the least amount of work on the OIDC side.

**Comment by spruce-bruce** [comment]
Some other things I've been thinking about

1. Template development should be easier for people who don't know all the ins and outs of OIDC. Designers should be able to pop into OIDC and have a way to work on the templates easily. Most of this stuff is pretty easy already, but it wouldn't be hard to serve the templates up with dummy client info to speed up the process.
2. The layout/theming is set up so that we could provide different "themes". Right now we have a default theme which is the one we're familiar with, but we can implement theming fairly easily. For each theme we'd need a file in the layout directory (we wouldn't even need to replace the other default templates). Some small amount of work would need to be done to allow clients to be configured to use different themes.
