### ISSUE TITLE
stop hardcoding nonce for resetPasswordSuccess

### ISSUE THREAD

**Issue by spruce-bruce** [synapsestudios/oidc-platform#138]
in the `user-views` file the `resetPasswordSuccess` function is hardcoding the nonce value. This should be updated to work the way it's supposed to work (ie, if nonce is provided use the provided value, otherwise don't set nonce)

This probably made it in as a developer temporary thing that never got caught

# Tasks
- [x] Add nonce as an optional parameter to the invite endpoint to be included in the set password link
- [x] Add nonce as an optional parameter to the re-invite endpoint
- [x] Use the nonce from the request query if there is one, otherwise exclude it

**Comment by spruce-bruce** [comment]
I think this is fixed

I have to go fix #149 to make sure that this works
