### ISSUE TITLE
Overriding Email Subject Line

### ISSUE THREAD

**Issue by msinnes** [synapsestudios/oidc-platform#200]
Invite emails currently have the subject line: `{{appName}} Invitation`.

We need a way to override this default behavior.

# Tasks
- [x] add a json `meta` (or some better name) to store template specific values
- [x] update theme service with `getTemplate` method that returns an object like `{renderedTemplate: /* html */, meta: {/*stuff*/}`
- [x] update user email functions to use the getTemplate function and override subject with subject from meta object if present

**Comment by spruce-bruce** [comment]
Got carried away and did all three tasks on one PR
