### ISSUE TITLE
Implement a system for webhooks

### ISSUE THREAD

**Issue by spruce-bruce** [synapsestudios/oidc-platform#203]
# Description
Clients will have a need to be alerted when user data changes. A webhook system should be built to allow clients to subscribe to events.

Using the webhook architecture documented here: https://zapier.com/engineering/webhook-design/

For MVP we'll need a `POST /api/webhook` endpoint.
- authenticate with client credentials and admin scope
- takes events to subscribe to (these will be like 'user.update', 'user.create', etc)
- takes a webhook_url that will be used to POST

The webhook service should be driver based so that we can support a couple different queue providers. The first driver we will build is simple in-memory queue (maybe with better-queue) or SQS.

The queue processor (when necessary) should be configured to run on the same container as the OIDC Provider. Whether or not there is a queue processor and what that processor is should be queue driver dependent.

The webhook service should be _optional_ when installing the Synapse OIDC Provider. Don't require any webhook config and don't maintain a webhook queue if webhooks are off.

The webhook service events should be documented in a new `EVENTS.md` file. The event required for MVP is `user.update` that fires when a user's profile or email is changed.

The webhook will POST the full resource that triggers the event as well as the event name, webhook id, timestamp, and a signed token (jwt probably). The token will be generated using the client id/secret and can be validated the same way the OIDC id tokens are validated.

webhook POST requests should retry when they fail. Retry config will be different depending on driver (some will support only simple "max retries" and "retry delay" config, others will let you do cool fancy stuff). 

Make sure to log POST attempts (success or fail) with a custom log level so we can stream those logs somewhere some day.

# Tasks
- [x] POST webhooks
- [x] set up queue factory function that allows for multiple queue adapters. write a single in-memory adapter with an enqueue method that does nothing
- [x] write a webhook service with a `trigger` method that takes an event name and a resource and enqueues the webhook
  - event name should be validated against a list of allowed events
- [x] write queue processing function the POST to the webhook endpoint - make sure retries are configurable
- [x] update queue processor to POST with ~a signed jwt~ some sort of reasonable auth. ~Basic auth with client id and secret is probably fine~ (changed my mind again).
- [x] ~get the server.log function down to the queue adapter somehow and~ log stuff that we care about
- [x] make webhooks optional
- [x] document!
- [x] call trigger in appropriate places
