### ISSUE TITLE
Add API endpoint for deleting a user

### ISSUE THREAD

**Issue by agerbens** [synapsestudios/oidc-platform#526]
## Description:
The motivation behind this change is that Apple is [going to start requiring account deletion within apps by January 31, 2022]((https://developer.apple.com/news/?id=mdkbobfo)). 

It's not entirely clear what all this entails, so to start this is going to be a very simple route that hard deletes a user from `SIP_user` and doesn't have any new screens or send any new emails.

## Tasks
- [ ] Add integration tests for a new route at DELETE /api/users/{user_id}
- [ ] Add the route
- [ ] Check the READMEs to see whether anything needs to be updated.
