### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by pcavagna** [synapsestudios/oidc-platform#59]
# DESCRIPTION
Change password

## Tasks
- [x] update template table to allow for the change password form and the change password success email
- [x] Create a GET endpoint that displays the change password screen
- [x] Create a POST endpoint for the change password form. Successfully changing a password should take the user to the register screen OR back to the app depending on some bool value or something in the query.
- [x] Successfully changing password should trigger a new email that warns the user that their password has been updated.

## Future stuff
Should this force the user to log back in? We could make use of back channel logout functionality to alert client apps that the user should be logged out.
